### ISSUE TITLE
question: can client be used inside vuex

### ISSUE THREAD

**Issue by sarodspirit** [logaretm/villus#117]
Hi all!
Im trying to useClient inside vuex with composition api.
In App.vue
```js
setup(){
useClient({url:process.env.VUE_APP_GRAPHQL_URL})
}
```
when I try to executeMutation or executeQuery in vuex.store i get 
```
 provide is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().
```
and 
```
Cannot read property 'execute' of undefined
```
Is this because there is no provider define in the store ?

**Comment by logaretm** [comment]
I didn't play around with vuex yet to give an educated opinion here, but the current workaround is to use the `client` API manually without any of the `useXXXX` functions because they are meant to be used with the composition API.

Here is the docs example:

https://villus.logaretm.com/api/client#queries

These snippets can be used anywhere, but of course, they are not as handy as the `useXXX` functions.

I don't think there is anything that villus can do to have Vuex supported somehow, I will have to re-evaluate as I familiarize myself with the new Vuex.

**Comment by sarodspirit** [comment]
@logaretm thanks.
I ended up having to createClient on vuex store to use it.
