### ISSUE TITLE
[Question] Query Batching is only on vue 3 ?

### ISSUE THREAD

**Issue by stephanedemotte** [logaretm/villus#15]
I use `"villus": "^0.3.0"` for vue 2 and query batching is not available.

In the doc, only `suspend` get the `only for vue 3.x` flag

Can we use the alpha version for vue 2 ?

Thanks !

**Comment by altitudems** [comment]
I am able to use the latest version with Vue 2, if I use the client directly, but I do get warnings about certain things missing from Vue. Is it possible to support Vue 2 better? Or at least using the composition api for vue 2? 
I am trying this instead of vue apollo, and so far its much better. Thanks for making this!

**Comment by logaretm** [comment]
I haven't got around to implementing it for Vue 2 composition plugin, will do at the weekend!

**Comment by logaretm** [comment]
Should be available in `0.4.0`
