### ISSUE TITLE
CombinedError Object property graphqlErrors is undefined

### ISSUE THREAD

**Issue by Lappihuan** [logaretm/villus#49]
It appears that the `CombinedError` Object does not set the `graphqlErrors` property:
![grafik](https://user-images.githubusercontent.com/7474162/94726766-fdcf5f80-035d-11eb-8664-0c284cb9d751.png)

The actual error is still accessible in the `response > body > errors` array

Expected behaviour would be that the `graphqlErrors` property of `CombinedError` holds a array of `GraphQLError` objects.

**Comment by logaretm** [comment]
Thanks for reporting this, From what I can tell it's because the status code is `400` as GraphQL spec doesn't care much for status code, and returning 200s even if errors exist is perfectly fine.

However I think villus should be adjusted to handle this as well, as I would imagine it is common to return response codes other than 200

**Comment by Lappihuan** [comment]
awesome thanks!
