### ISSUE TITLE
updating UI after a mutation

### ISSUE THREAD

**Issue by blocka** [logaretm/villus#8]
How would you update the UI after a mutation? One of apollo's most useful features is that you return entities that you would like updated after mutation, and the UI is just magically updated. Is there a pattern for this using this library?

**Comment by logaretm** [comment]
You mean like `refetchQueries`? So far there is not a way to do that at the moment, but you can compose that behvaior like this:

```js
const { execute, data } = useQuery({
  // ...
});

const mutation = useMutation({
  // ...
});

const executeMutation = mutation.execute;
// patch the mutation execute method to call the queries
mutation.execute = (...args) => {
  return executeMutation(...args).then(() => execute());
}

return { ...mutation, data, execute };
```

I know its not super neat like apollo, but the scope of this library is intentionally small, so stuff like this will take a lot of consideration before implementing it.

But I think adding this won't add a lot of boilerplate to the code, will experiment and report back.

**Comment by blocka** [comment]
Well not exactly refetchQueries
With Apollo you update the ui with data returned from the mutation...no
need to make another request.

**Comment by logaretm** [comment]
Oh sorry, got it. Sadly stuff like that is definitely out of scope because apollo tracks entities by ids and is able to tell that a mutation changed any of the fetched entities. this is one of the things I'm avoiding in this library to avoid overheads.

I will try to add a **cookbook** of sorts on how to implement these things yourself to the docs.
